# -*- coding: utf-8 -*-
"""Salary_Pro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12qRhNSrI_O0k2_N2PlrwLF1srwbCflGv

# **Salary Projection with Machine Learning**
by Fathimah Aulia
"""

import pandas as pd

from google.colab import files

data = files.upload()
df = pd.read_csv(next(iter(data)))

df.info()

x = df.iloc[:, :-1]
y = df.iloc[:, 1]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=1/3, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train.values, y_train.values)

import matplotlib.pyplot as plt
plt.scatter(x_train, y_train, color='blue')
plt.plot(x_train, regressor.predict(x_train), color='red')
plt.title("Years Experience vs Salary")
plt.xlabel("Years Experience")
plt.ylabel("Salary")
plt.show()

plt.scatter(x_test, y_test, color='blue')
plt.plot(x_test, regressor.predict(x_test), color='red')
plt.title("Years Experience vs Salary")
plt.xlabel("Years Experience")
plt.ylabel("Salary")
plt.show()

"""**MAKE NEW PREDICTION**"""

salary_pred = regressor.predict([[15]])
print("The salary for that amount of years experience is", salary_pred)